final: main.o strcat.o strcmp.o strcpy.o
	gcc main.o strcat.o strcmp.o strcpy.o -o final
main.o: main.c
	gcc -c main.c
strcat.o: strcat.c
	gcc -c strcat.c
strcmp.o: strcmp.c
	gcc -c strcmp.c
strcpy.o: strcpy.c
	gcc -c  strcpy.c
clean:
	rm *.o main

